PUT http://localhost:8080/events/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA3OTAwMTU0LCJ1c2VySWQiOjJ9.NT0tURUBDHWZKfEN-wTv3eaBp6OnWpcY0HrrzjNG9T8

{
    "name": "Updated test event",
    "description": "A test Event",
    "location": "Test Location (Updated)",
    "dateTime": "2025-01-01T15:30:00Z"
}